version: "3.8"

services:

  web: 
    build: .
    command: python /test_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/docker_projects
    ports:
      - 8000:8000

    depends_on:
       - db
  db:
    image: postgres:14.1-alpine

    environment:
      - POSTGRES_DB=test_erg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432