# Generated by Django 3.0.14 on 2022-06-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.CharField(max_length=126, verbose_name='tag'),
        ),
    ]
